"""add workshop bank accounts, mobile payments, payment fields to part_payments

Revision ID: 17d84f77383b
Revises: f69dbaeed5ca
Create Date: 2026-06-23 08:32:26.337664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17d84f77383b"
down_revision: Union[str, Sequence[str], None] = "f69dbaeed5ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workshop_bank_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workshop_id", sa.UUID(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=False),
        sa.Column("holder_ci", sa.String(), nullable=False),
        sa.Column("bank_name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workshop_mobile_payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workshop_id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("bank_name", sa.String(), nullable=False),
        sa.Column("holder_ci", sa.String(), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "part_payments", sa.Column("payment_method", sa.String(), nullable=False)
    )
    op.add_column(
        "part_payments", sa.Column("reference_number", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("part_payments", "reference_number")
    op.drop_column("part_payments", "payment_method")
    op.drop_table("workshop_mobile_payments")
    op.drop_table("workshop_bank_accounts")
    # ### end Alembic commands ###
