"""add vehicle_id and mileage to part_purchases

Revision ID: 70489c937aeb
Revises: 17d84f77383b
Create Date: 2026-06-23 11:39:42.230912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70489c937aeb"
down_revision: Union[str, Sequence[str], None] = "17d84f77383b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("part_purchases", sa.Column("vehicle_id", sa.UUID(), nullable=False))
    op.add_column("part_purchases", sa.Column("mileage", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "part_purchases", "vehicles", ["vehicle_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "part_purchases", type_="foreignkey")
    op.drop_column("part_purchases", "mileage")
    op.drop_column("part_purchases", "vehicle_id")
    # ### end Alembic commands ###
