"""add carts, cart_items, vehicle_id+mileage to orders

Revision ID: 8974be621000
Revises: 6dcc7e96923f
Create Date: 2026-06-23 11:59:11.766697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8974be621000"
down_revision: Union[str, Sequence[str], None] = "6dcc7e96923f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("part_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("orders", sa.Column("vehicle_id", sa.UUID(), nullable=False))
    op.add_column("orders", sa.Column("mileage", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "orders", "vehicles", ["vehicle_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "mileage")
    op.drop_column("orders", "vehicle_id")
    op.drop_table("cart_items")
    op.drop_table("carts")
    # ### end Alembic commands ###
