"""add part category, installment_min_percentage, is_active, part_purchases, part_payments

Revision ID: f69dbaeed5ca
Revises: 0b1f2e984b23
Create Date: 2026-06-23 08:24:50.229337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f69dbaeed5ca"
down_revision: Union[str, Sequence[str], None] = "0b1f2e984b23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "part_purchases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("part_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workshop_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("down_payment", sa.Float(), nullable=False),
        sa.Column("financed_amount", sa.Float(), nullable=False),
        sa.Column("installment_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "part_payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("purchase_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["part_purchases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("parts", sa.Column("category", sa.String(), nullable=True))
    op.add_column(
        "parts", sa.Column("installment_min_percentage", sa.Float(), nullable=False)
    )
    op.add_column("parts", sa.Column("is_active", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parts", "is_active")
    op.drop_column("parts", "installment_min_percentage")
    op.drop_column("parts", "category")
    op.drop_table("part_payments")
    op.drop_table("part_purchases")
    # ### end Alembic commands ###
