from enum import StrEnum


class VenezuelanBank(StrEnum):
    BANCO_DE_VENEZUELA = "Banco de Venezuela"
    VENEZOLANO_DE_CREDITO = "Venezolano de Crédito"
    MERCANTIL = "Mercantil Banco"
    PROVINCIAL = "BBVA Provincial"
    BANCARIBE = "Bancaribe"
    EXTERIOR = "Banco Exterior"
    CARONI = "Banco Caroní"
    BANESCO = "Banesco"
    SOFITASA = "Banco Sofitasa"
    PLAZA = "Banco Plaza"
    BANGENTE = "Bangente"
    FONDO_COMUN = "BFC Banco Fondo Común"
    BANCO_100 = "100% Banco"
    DEL_SUR = "DelSur"
    DEL_TESORO = "Banco del Tesoro"
    AGRICOLA = "Banco Agrícola de Venezuela"
    BANCRECER = "Bancrecer"
    MI_BANCO = "R4 (Mi Banco)"
    ACTIVO = "Banco Activo"
    BANCAMIGA = "Bancamiga"
    INTERNACIONAL_DESARROLLO = "Banco Internacional de Desarrollo"
    BANPLUS = "Banplus"
    BICENTENARIO = "Banco Digital de los Trabajadores (Bicentenario)"
    BANFANB = "BANFANB"
    N58 = "N58 Banco Digital"
    BNC = "Banco Nacional de Crédito (BNC)"
